import type { Product } from "@/types/product"

export const PRODUCTOS_DB: Record<string, Product> = {
  "AirPods Pro 2da Gen": {
    categoria: "Accesorios Apple",
    descripcion: "Auriculares inalámbricos con cancelación activa de ruido y calidad de sonido premium.",
    detalles: [
      "Cancelación activa de ruido",
      "Audio espacial personalizado",
      "Resistente al agua y sudor",
      "Hasta 6 horas de reproducción con una sola carga",
      "Estuche de carga inalámbrica incluido",
    ],
    precios: [
      { tier: "5x", price: 13.3 },
      { tier: "10x", price: 12.8 },
      { tier: "20x", price: 11.5 },
      { tier: "30x", price: 10.5 },
      { tier: "40x", price: 10.0 },
      { tier: "100x", price: 9.5 },
      { tier: "200x", price: 9.0 },
      { tier: "500x", price: 8.5 },
    ],
  },
  "Cable + Cargador": {
    categoria: "Accesorios Apple",
    descripcion: "Set de cable Lightning y cargador USB-C de 20W de Apple para carga rápida de dispositivos.",
    detalles: [
      "Adaptador de corriente USB-C de 20W original Apple",
      "Cable de carga rápida Lightning a USB-C",
      "Protección contra sobrecarga",
      "Longitud del cable: 1 metro",
      "Compatible con iPhone y iPad",
    ],
    precios: [
      { tier: "5x", price: 5.5 },
      { tier: "10x", price: 5.0 },
      { tier: "20x", price: 4.5 },
      { tier: "30x", price: 4.1 },
      { tier: "50x", price: 3.7 },
      { tier: "100x", price: 3.2 },
    ],
  },
  "Cargadores Completos": {
    categoria: "Accesorios Apple",
    descripcion: "Kit completo de cargador Apple con adaptador USB-C de 20W y cable USB-C a Lightning.",
    detalles: [
      "Adaptador de corriente USB-C de 20W original Apple",
      "Cable USB-C a Lightning incluido",
      "Tecnología de carga rápida",
      "Compatible con todos los modelos de iPhone",
      "Diseño compacto y portátil",
    ],
    precios: [
      { tier: "5x", price: 5.5 },
      { tier: "10x", price: 5.0 },
      { tier: "20x", price: 4.5 },
      { tier: "30x", price: 4.1 },
      { tier: "50x", price: 3.7 },
      { tier: "100x", price: 3.2 },
    ],
  },
  "Battery Pack 🔋": {
    categoria: "Accesorios Apple",
    descripcion: "Batería externa MagSafe oficial de Apple para iPhone, con diseño compacto y carga inalámbrica.",
    detalles: [
      "Batería externa MagSafe oficial de Apple",
      "Compatible con iPhone 12 y posteriores",
      "Carga inalámbrica magnética",
      "Diseño ultradelgado y ligero",
      "Integración perfecta con iOS",
    ],
    precios: [
      { tier: "5x", price: 10.0 },
      { tier: "10x", price: 9.5 },
      { tier: "20x", price: 9.0 },
      { tier: "30x", price: 8.5 },
      { tier: "50x", price: 8.0 },
    ],
  },
  "Funda Silicon Case I11 - 16Pro Max 📱": {
    categoria: "Accesorios Apple",
    descripcion: "Fundas de silicona premium para iPhone, desde el modelo 11 hasta el 16 Pro Max.",
    detalles: [
      "Material: Silicona de alta calidad",
      "Interior de microfibra",
      "Protección completa para el dispositivo",
      "Diseño delgado que no añade volumen",
      "Disponible en varios colores",
    ],
    precios: [
      { tier: "15x", price: 2.5 },
      { tier: "25x", price: 2.2 },
      { tier: "50x", price: 1.8 },
      { tier: "75x", price: 1.7 },
      { tier: "100x", price: 1.5 },
      { tier: "300x", price: 1.3 },
    ],
  },
  "AirPods Max 🎧": {
    categoria: "Accesorios Apple",
    descripcion: "Auriculares over-ear premium de Apple con cancelación activa de ruido y audio espacial.",
    detalles: [
      "Cancelación activa de ruido de alta fidelidad",
      "Audio espacial con seguimiento dinámico de cabeza",
      "Chip H1 de Apple para audio computacional",
      "Hasta 20 horas de reproducción",
      "Diseño over-ear con almohadillas de malla acústica",
      "Digital Crown para control preciso del volumen",
    ],
    precios: [
      { tier: "5x", price: 16.0 },
      { tier: "10x", price: 15.0 },
      { tier: "20x", price: 14.0 },
      { tier: "50x", price: 13.0 },
    ],
  },
  "JBL GO3": {
    categoria: "Varios",
    descripcion: "Altavoz portátil JBL GO3 con sonido potente y diseño compacto en varios colores.",
    detalles: [
      "Bluetooth 5.1",
      "Resistente al agua (IPX7)",
      "Duración de batería: 3 horas",
      "Diseño ultraportátil",
      "Colores surtidos disponibles",
    ],
    precios: [
      { tier: "5x", price: 11.0 },
      { tier: "10x", price: 10.5 },
      { tier: "20x", price: 10.0 },
      { tier: "40x", price: 9.5 },
      { tier: "60x", price: 9.0 },
      { tier: "100x", price: 8.5 },
    ],
  },
  "​Aspiradora Robot 🤖": {
    categoria: "Varios",
    descripcion: "Aspiradora robot inteligente SWEEPOL con navegación avanzada y control automático. ¡LIQUIDACIÓN!",
    detalles: [
      "Navegación inteligente con sensores",
      "Limpieza automática programable",
      "Batería de larga duración",
      "Sistema de filtrado avanzado",
      "Diseño compacto y silencioso",
      "Retorno automático a base de carga",
      "Disponible en negro y blanco",
      "¡PRECIO DE LIQUIDACIÓN!",
    ],
    precios: [{ tier: "1x", price: 16.0 }],
  },
  "Torch 7.5G 🌸": {
    categoria: "Vapes",
    descripcion: "Vape desechable con sabores premium y diseño elegante en varios colores.",
    detalles: [
      "7500 inhalaciones aproximadas",
      "Batería de larga duración",
      "Disponible en varios colores y sabores",
      "Diseño compacto y portátil",
      "Experiencia de vapor suave",
    ],
    precios: [
      { tier: "5x", price: 30.0 },
      { tier: "10x", price: 29.5 },
      { tier: "25x", price: 29.0 },
      { tier: "50x", price: 28.0 },
      { tier: "100x", price: 27.0 },
    ],
  },
  "ElfThc 5g Edición Limitada 💨": {
    categoria: "Vapes",
    descripcion: "Vape desechable premium con 5g de contenido, edición limitada con efectos especiales.",
    detalles: [
      "5g de contenido premium",
      "Edición limitada especial",
      "Efectos potenciados",
      "Diseño exclusivo",
      "Experiencia única",
    ],
    precios: [
      { tier: "5x", price: 26.5 },
      { tier: "10x", price: 25.5 },
      { tier: "15x", price: 24.5 },
      { tier: "25x", price: 23.5 },
      { tier: "50x", price: 22.0 },
      { tier: "100x", price: 21.5 },
    ],
  },
  "ElfThc 3000mg Edición Limitada 💨": {
    categoria: "Vapes",
    descripcion: "Vape desechable con 3000mg de contenido activo, edición limitada con fórmula especial.",
    detalles: [
      "3000mg de contenido activo",
      "Edición limitada especial",
      "Fórmula mejorada",
      "Efectos duraderos",
      "Diseño premium",
    ],
    precios: [
      { tier: "5x", price: 19.0 },
      { tier: "10x", price: 18.5 },
      { tier: "20x", price: 18.0 },
      { tier: "30x", price: 17.5 },
      { tier: "50x", price: 17.0 },
      { tier: "100x", price: 16.0 },
    ],
  },
  "Elfbar 40K Puff 💨": {
    categoria: "Vapes",
    descripcion: "Vape desechable Sour King con hasta 40.000 inhalaciones y sabores intensos.",
    detalles: [
      "40.000 inhalaciones aproximadas",
      "Sistema de malla para mejor sabor",
      "Sabores premium como Sour Blue Razz Ice",
      "Batería recargable incorporada",
      "4 niveles personalizados de intensidad",
    ],
    precios: [
      { tier: "5x", price: 13.8 },
      { tier: "10x", price: 13.3 },
      { tier: "20x", price: 12.8 },
      { tier: "50x", price: 12.0 },
      { tier: "100x", price: 11.75 },
    ],
  },
  "Ignite V400 40mil 💨": {
    categoria: "Vapes",
    descripcion: "Vape desechable premium con 40.000 inhalaciones y tecnología V400 avanzada.",
    detalles: [
      "40.000 inhalaciones aproximadas",
      "Tecnología V400 avanzada",
      "Diseño premium y ergonómico",
      "Batería de ultra larga duración",
      "Sistema de calentamiento optimizado",
      "Sabores intensos y duraderos",
    ],
    precios: [
      { tier: "5x", price: 15.5 },
      { tier: "10x", price: 15.0 },
      { tier: "20x", price: 14.5 },
      { tier: "30x", price: 14.25 },
      { tier: "50x", price: 13.8 },
    ],
  },
  "Lost Mary Mixer 30.000 Puffs 💨": {
    categoria: "Vapes",
    descripcion: "Vape desechable con sistema de mezcla de sabores dobles y hasta 30.000 inhalaciones.",
    detalles: [
      "30.000 inhalaciones aproximadas",
      "Sistema de doble sabor ajustable",
      "Diseño ergonómico en varios colores",
      "Experiencia de vapor consistente",
      "Variedad de sabores disponibles",
    ],
    precios: [
      { tier: "5x", price: 13.5 },
      { tier: "10x", price: 13.0 },
      { tier: "20x", price: 12.7 },
      { tier: "30x", price: 12.2 },
      { tier: "50x", price: 11.8 },
      { tier: "100x", price: 11.4 },
    ],
  },
  "IGNITE V250 25.000 Puffs 💨": {
    categoria: "Vapes",
    descripcion: "Vape desechable premium con diseño holográfico y 25.000 inhalaciones.",
    detalles: [
      "25.000 inhalaciones aproximadas",
      "Diseño ultra slim con acabado holográfico",
      "Tecnología de boost para mayor intensidad",
      "Batería de larga duración de 650mAh",
      "Variedad de sabores refrescantes",
    ],
    precios: [
      { tier: "5x", price: 13.7 },
      { tier: "10x", price: 13.2 },
      { tier: "20x", price: 12.8 },
      { tier: "40x", price: 12.3 },
      { tier: "60x", price: 11.8 },
      { tier: "100x", price: 11.4 },
    ],
  },
  "IGNITE V150 15.000 Puffs 💨": {
    categoria: "Vapes",
    descripcion: "Vape compacto con diseño holográfico y 15.000 inhalaciones en sabores refrescantes.",
    detalles: [
      "15.000 inhalaciones aproximadas",
      "Diseño ultra slim con acabado holográfico",
      "Tecnología de calentamiento avanzada",
      "Sistema anti-fugas",
      "Variedad de sabores disponibles",
    ],
    precios: [
      { tier: "5x", price: 11.0 },
      { tier: "10x", price: 10.8 },
      { tier: "20x", price: 10.3 },
      { tier: "40x", price: 9.8 },
      { tier: "60x", price: 9.4 },
      { tier: "100x", price: 8.8 },
    ],
  },
  "Elfbar Ice King 40.000 Puffs 💨": {
    categoria: "Vapes",
    descripcion: "Vape desechable premium con hasta 40.000 inhalaciones y sabores helados intensos.",
    detalles: [
      "40.000 inhalaciones aproximadas",
      "Sistema de enfriamiento Ice King",
      "Batería recargable de larga duración",
      "5 niveles de intensidad ajustables",
      "Variedad de sabores helados",
    ],
    precios: [
      { tier: "5x", price: 15.0 },
      { tier: "10x", price: 14.5 },
      { tier: "20x", price: 14.0 },
      { tier: "40x", price: 13.5 },
      { tier: "60x", price: 13.0 },
      { tier: "100x", price: 12.5 },
    ],
  },
  "AL HARAMAIN AMBER OUD GOLD EDITION EDP 100ml 🌟": {
    categoria: "Perfumes",
    descripcion: "Perfume premium árabe con notas de ámbar y oud, presentación de lujo en caja dorada.",
    detalles: [
      "Eau de Parfum 100ml",
      "Notas principales: Ámbar, Oud, especias orientales",
      "Larga duración y gran proyección",
      "Presentación premium en caja de lujo",
      "Fragancia unisex de alta gama",
    ],
    rangosPerfume: [
      { min: 3, max: 4, price: 62.5 },
      { min: 5, max: 9, price: 60.5 },
      { min: 10, max: 19, price: 60.0 },
      { min: 20, max: Number.POSITIVE_INFINITY, price: 59.5 },
    ],
  },
  "BHARARA KING EDP 150ml 👑": {
    categoria: "Perfumes",
    descripcion: "Fragancia masculina de lujo con 150ml de contenido, diseño elegante y sofisticado.",
    detalles: [
      "Eau de Parfum 150ml",
      "Fragancia masculina de alta gama",
      "Notas frescas y amaderadas",
      "Presentación elegante en caja plateada",
      "Larga duración y excelente proyección",
    ],
    rangosPerfume: [
      { min: 3, max: 4, price: 68.5 },
      { min: 5, max: 9, price: 66.5 },
      { min: 10, max: 19, price: 66.0 },
      { min: 20, max: Number.POSITIVE_INFINITY, price: 65.5 },
    ],
  },
  "LATTAFA FAKHAR DORADO EDP 100ml ✨": {
    categoria: "Perfumes",
    descripcion: "Perfume árabe con diseño dorado ornamentado, fragancia oriental de lujo.",
    detalles: [
      "Eau de Parfum 100ml",
      "Fragancia oriental con notas especiadas",
      "Diseño árabe tradicional dorado",
      "Excelente duración y sillage",
      "Perfume unisex de alta calidad",
    ],
    rangosPerfume: [
      { min: 3, max: 4, price: 36.5 },
      { min: 5, max: 9, price: 35.0 },
      { min: 10, max: 19, price: 34.0 },
      { min: 20, max: Number.POSITIVE_INFINITY, price: 33.5 },
    ],
  },
  "ARMAF CLUB DE NUIT INTENSE MAN EDT 105ml 🖤": {
    categoria: "Perfumes",
    descripcion: "Fragancia masculina intensa inspirada en los grandes clásicos, presentación elegante.",
    detalles: [
      "Eau de Toilette 105ml",
      "Fragancia masculina intensa",
      "Notas cítricas, especiadas y amaderadas",
      "Inspirado en fragancias de lujo",
      "Excelente relación calidad-precio",
    ],
    rangosPerfume: [
      { min: 3, max: 4, price: 35.5 },
      { min: 5, max: 9, price: 33.5 },
      { min: 10, max: 19, price: 33.0 },
      { min: 20, max: Number.POSITIVE_INFINITY, price: 32.5 },
    ],
  },
  "LATTAFA KHAMRAH EDP 100ml 🍯": {
    categoria: "Perfumes",
    descripcion: "Perfume dulce y especiado con notas de canela, vainilla y ámbar, muy popular.",
    detalles: [
      "Eau de Parfum 100ml",
      "Notas principales: Canela, vainilla, ámbar",
      "Fragancia dulce y especiada",
      "Muy popular entre jóvenes",
      "Excelente duración y proyección",
    ],
    rangosPerfume: [
      { min: 3, max: 4, price: 42.0 },
      { min: 5, max: 9, price: 40.0 },
      { min: 10, max: 19, price: 39.5 },
      { min: 20, max: Number.POSITIVE_INFINITY, price: 39.0 },
    ],
  },
  "LATTAFA ASAD EDP 100ml 🦁": {
    categoria: "Perfumes",
    descripcion: "Fragancia masculina potente con diseño de medallón dorado, notas orientales intensas.",
    detalles: [
      "Eau de Parfum 100ml",
      "Fragancia masculina oriental",
      "Notas intensas y especiadas",
      "Diseño con medallón dorado distintivo",
      "Gran proyección y duración",
    ],
    rangosPerfume: [
      { min: 3, max: 4, price: 29.5 },
      { min: 5, max: 9, price: 27.5 },
      { min: 10, max: 19, price: 27.0 },
      { min: 20, max: Number.POSITIVE_INFINITY, price: 26.5 },
    ],
  },
  "LATTAFA BADE'E AL OUD SUBLIME 100ml 🌹": {
    categoria: "Perfumes",
    descripcion: "Perfume árabe tradicional con oud sublime, presentación lujosa en caja roja.",
    detalles: [
      "Eau de Parfum 100ml",
      "Notas principales: Oud, rosa, especias",
      "Fragancia árabe tradicional",
      "Presentación lujosa en caja roja",
      "Perfume unisex de alta calidad",
    ],
    rangosPerfume: [
      { min: 3, max: 4, price: 29.5 },
      { min: 5, max: 9, price: 27.5 },
      { min: 10, max: 19, price: 27.0 },
      { min: 20, max: Number.POSITIVE_INFINITY, price: 26.5 },
    ],
  },
  "LATTAFA YARA PINK EDP 100ml 🌸": {
    categoria: "Perfumes",
    descripcion: "Fragancia femenina dulce y floral en elegante presentación rosa, muy popular.",
    detalles: [
      "Eau de Parfum 100ml",
      "Fragancia femenina dulce y floral",
      "Notas de frutas y flores",
      "Presentación elegante en rosa",
      "Muy popular entre mujeres jóvenes",
    ],
    rangosPerfume: [
      { min: 3, max: 4, price: 36.0 },
      { min: 5, max: 9, price: 34.0 },
      { min: 10, max: 19, price: 33.5 },
      { min: 20, max: Number.POSITIVE_INFINITY, price: 33.0 },
    ],
  },
  "LATTAFA YARA CANDY EDP 100ml 🍭": {
    categoria: "Perfumes",
    descripcion: "Versión dulce de Yara con notas gourmand, perfecta para quienes aman las fragancias dulces.",
    detalles: [
      "Eau de Parfum 100ml",
      "Fragancia gourmand muy dulce",
      "Notas de caramelo y vainilla",
      "Versión especial de la línea Yara",
      "Ideal para amantes de lo dulce",
    ],
    rangosPerfume: [
      { min: 3, max: 4, price: 28.5 },
      { min: 5, max: 9, price: 26.5 },
      { min: 10, max: 19, price: 26.0 },
      { min: 20, max: Number.POSITIVE_INFINITY, price: 25.5 },
    ],
  },
  "LATTAFA YARA MOI EDP 100ml 💖": {
    categoria: "Perfumes",
    descripcion: "Otra variación de la popular línea Yara, con notas florales y frutales equilibradas.",
    detalles: [
      "Eau de Parfum 100ml",
      "Fragancia floral-frutal equilibrada",
      "Parte de la exitosa línea Yara",
      "Notas frescas y femeninas",
      "Excelente duración y proyección",
    ],
    rangosPerfume: [
      { min: 3, max: 4, price: 29.0 },
      { min: 5, max: 9, price: 27.0 },
      { min: 10, max: 19, price: 26.5 },
      { min: 20, max: Number.POSITIVE_INFINITY, price: 26.0 },
    ],
  },
  "LATTAFA BADEE AL OUD NOBLE BLUSH EDP 100ml 🌺": {
    categoria: "Perfumes",
    descripcion: "Perfume árabe con oud noble y notas florales, fragancia sofisticada y elegante.",
    detalles: [
      "Eau de Parfum 100ml",
      "Notas principales: Oud noble, flores",
      "Fragancia sofisticada y elegante",
      "Combinación perfecta de tradición y modernidad",
      "Perfume unisex de alta gama",
    ],
    rangosPerfume: [
      { min: 3, max: 4, price: 31.5 },
      { min: 5, max: 9, price: 29.5 },
      { min: 10, max: 19, price: 29.0 },
      { min: 20, max: Number.POSITIVE_INFINITY, price: 28.5 },
    ],
  },
  "LATTAFA FAKHAR ROSE EDP 100ml 🌹": {
    categoria: "Perfumes",
    descripcion: "Versión rosa de Fakhar con notas florales predominantes, elegancia en estado puro.",
    detalles: [
      "Eau de Parfum 100ml",
      "Notas principales: Rosa, flores orientales",
      "Versión floral de la línea Fakhar",
      "Fragancia elegante y sofisticada",
      "Perfecta para ocasiones especiales",
    ],
    rangosPerfume: [
      { min: 3, max: 4, price: 36.0 },
      { min: 5, max: 9, price: 34.0 },
      { min: 10, max: 19, price: 33.5 },
      { min: 20, max: Number.POSITIVE_INFINITY, price: 33.0 },
    ],
  },
}
